Fiap05.Web.MVC/Fiap05.Web.MVC/Models/CartaoReal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap05.Web.MVC.Models
{
    public class CartaoReal
    {
        public int CartaoRealId { get; set; }
        public long Numero { get; set; }
        public int CVV { get; set; }

        public StatusCartao Status { get; set; }

        //Relacionamentos
        public IList<CartaoVirtual> CartoesVirtuais { get; set; }
    }
}

Fiap05.Web.MVC/Fiap05.Web.MVC/Models/CartaoVirtual.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap05.Web.MVC.Models
{
    public class CartaoVirtual
    {
        public int CartaoVirtualId { get; set; }
        public long Numero { get; set; }
        public bool Utilizado { get; set; }

        //Relacionamentos
        public CartaoReal CartaoReal { get; set; }
        public int CartaoRealId { get; set; }
    }
}

Fiap05.Web.MVC/Fiap05.Web.MVC/Models/Compra.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap05.Web.MVC.Models
{
    public class Compra
    {
        public int CompraId { get; set; }
        public DateTime Data { get; set; }

        //Relacionamentos
        public CartaoVirtual CartaoVirtual { get; set; }
        public int CartaoVirtualId { get; set; }
    }
}

Fiap05.Web.MVC/Fiap05.Web.MVC/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap05.Web.MVC.Models
{
    public class Produto
    {
        public int ProdutoId { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        //Relacionamentos
        public IList<Compra> Compras { get; set; }
    }
}

Fiap05.Web.MVC/Fiap05.Web.MVC/Models/StatusCartao.cs
namespace Fiap05.Web.MVC.Models
{
    public enum StatusCartao
    {
        Bloqueado, Aprovado, Cancelado
    }
}

Fiap05.Web.MVC/Fiap05.Web.MVC/Controllers/CartaoRealController.cs
using Fiap05.Web.MVC.Models;
using Fiap05.Web.MVC.Persistencia;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap05.Web.MVC.Controllers
{
    public class CartaoRealController : Controller
    {
        private FiapBankContext _context = new FiapBankContext();


        [HttpPost]
        public ActionResult Bloquear(int id)
        {
            var cartao = _context.CartoeReais.Find(id);
            if (cartao.Status == StatusCartao.Aprovado)
            {
                cartao.Status = StatusCartao.Bloqueado;
                _context.Entry(cartao).State = EntityState.Modified;
                _context.SaveChanges();
                TempData["msg"] = "Cartão bloqueado!";
            }

            return RedirectToAction("Listar");
        }


        [HttpPost]
        public ActionResult Aprovar(int id)
        {
            var cartao = _context.CartoeReais.Find(id);
            if(cartao.Status == StatusCartao.Bloqueado)
            {
                cartao.Status = StatusCartao.Aprovado;
                _context.Entry(cartao).State = EntityState.Modified;
                _context.SaveChanges();
                TempData["msg"] = "Cartão aprovado!";
            }

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult Listar()
        {
            var lista = _context.CartoeReais.ToList();
            return View(lista);
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(CartaoReal cartao)
        {
            cartao.Status = StatusCartao.Bloqueado;
            _context.CartoeReais.Add(cartao);
            _context.SaveChanges();
            TempData["msg"] = "Cartão real cadastrado com sucesso!!";
            return RedirectToAction("cadastrar");
        }
    }
}

Fiap05.Web.MVC/Fiap05.Web.MVC/Controllers/CartaoVirtualController.cs
using Fiap05.Web.MVC.Models;
using Fiap05.Web.MVC.Persistencia;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap05.Web.MVC.Controllers
{
    public class CartaoVirtualController : Controller
    {
        private FiapBankContext _context = new FiapBankContext();

        [HttpGet]
        public ActionResult Pesquisar(int numero)
        {
            var lista = _context.CartoesVirtuais.Where(c => c.CartaoRealId == numero).ToList();
            CarregarDropDown();


            //pagina listar, com a lista de cartões virtuais
            return View("Listar", lista);
        }

        private void CarregarDropDown()
        {
            var dropLista = _context.CartoeReais.ToList();
            ViewBag.listaCartao = new SelectList(dropLista, "CartaoRealId", "Numero");
        }

        [HttpGet]
        public ActionResult Listar()
        {
            var lista = _context.CartoesVirtuais.Include("CartaoReal").ToList();
            //valores para dropdown
            var dropLista = _context.CartoeReais.ToList();
            ViewBag.listaCartao = new SelectList(dropLista, "CartaoRealId", "Numero");
            return View(lista);
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            //Buscar todos os cartoes reais do banco
            var lista = _context.CartoeReais.ToList();
            //Enviar para a pag através do viewbag
            ViewBag.listaCartao = new SelectList(lista, "CartaoRealId", "Numero");
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(CartaoVirtual cartao)
        {
            _context.CartoesVirtuais.Add(cartao);
            _context.SaveChanges();
            TempData["msg"] = "Cartão virtual cadastrado com sucesso!";
            return RedirectToAction("Cadastrar");
        }
    }
}

Fiap05.Web.MVC/Fiap05.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FIAP BANK", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cartões Reais <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastrar", "Cadastrar", "CartaoReal")</li>
                            <li>@Html.ActionLink("Cartões", "Listar", "CartaoReal")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cartões Virtuais <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cartões", "Listar", "CartaoVirtual")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("Cadastrar", "Cadastrar", "CartaoVirtual")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>