Fiap08.Web.MVC/Fiap08.Web.MVC/Models/Patrocinador.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap08.Web.MVC.Models
{
    public class Patrocinador
    {
        public int PatrocinadorId { get; set; }
        public string Nome { get; set; }

        public IList<Projeto> Projetos { get; set; }
    }
}

Fiap08.Web.MVC/Fiap08.Web.MVC/Models/Projeto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap08.Web.MVC.Models
{
    public class Projeto
    {
        public int ProjetoId { get; set; }
        public string Titulo { get; set; }
        public decimal MetaInvestimento { get; set; }
        public DateTime DataLimite { get; set; }
        public decimal InvestimentoAtual { get; set; }
        public bool DeducaoIR { get; set; }

        public Patrocinador Patrocinador { get; set; }
        public int PatrocinadorId { get; set; }
    }
}

Fiap08.Web.MVC/Fiap08.Web.MVC/Controllers/PatrocinadorController.cs
using Fiap08.Web.MVC.Models;
using Fiap08.Web.MVC.Units;
using Fiap08.Web.MVC.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap08.Web.MVC.Controllers
{
    public class PatrocinadorController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        [HttpGet]
        public ActionResult Cadastrar()
        {
            var viewModel = new PatrocinadorViewModel();
            viewModel.Patrocinadores = _unit.PatrocinadorRepository.Listar();
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Cadastrar(Patrocinador patrocinador)
        {
            _unit.PatrocinadorRepository.Cadastrar(patrocinador);
            _unit.Salvar();
            TempData["msg"] = "Cadastrou";
            return RedirectToAction("Cadastrar");
        }

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
    }
}

Fiap08.Web.MVC/Fiap08.Web.MVC/Controllers/ProjetoController.cs
using Fiap08.Web.MVC.Models;
using Fiap08.Web.MVC.Units;
using Fiap08.Web.MVC.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap08.Web.MVC.Controllers
{
    public class ProjetoController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        [HttpPost]
        public ActionResult Cadastrar(Projeto projeto)
        {
            _unit.ProjetoRepository.Cadastrar(projeto);
            _unit.Salvar();
            TempData["msg"] = "Projeto Cadastrado!";
            return RedirectToAction("Cadastrar");
        }

        // GET: Projeto
        [HttpGet]
        public ActionResult Cadastrar()
        {
            var viewModel = new ProjetoViewModel();
            viewModel.Patrocinadores = new SelectList(_unit.PatrocinadorRepository.Listar(),
                "PatrocinadorId", "Nome");
            return View(viewModel);
        }

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
    }
}

Fiap08.Web.MVC/Fiap08.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | FIAP Starter</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FIAP Starter", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Patrocinador <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastrar","Cadastrar","Patrocinador")</li>                           
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>